on:
    workflow_dispatch:
    schedule:
        - cron: '0 */1 * * *' # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Run jira Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: jira
                port_client_id: imDYobGss2xTm09QpxrxLsl5FKkCrhad
                port_client_secret: jCHM2oO356tYpX3MZC8Gp3dsIwTy2N8uQrag1Q1e4g1exnPHXG6CfcNAt5A4RcEq
                config: |
                    jiraHost: https://samuelshorun.atlassian.net/
                    atlassianUserEmail: samuelshorun@gmail.com
                    atlassianUserToken: ATATT3xFfGF0ZqZ6hbgsldtye-TqPZ_a6OlC7GIX4HtejSQTXRYXNjNs-izDkX4gzSFFLavC4CcRUcg1gC4PVdGOaRVuvY55e_eo9LczGLoB8jm9KP2LNOxE-z94wTv_CYWi7Kfp-6wpdsz6RGlfK6BrGFcNqBmB5fE3xWknSTf7Sv4tvFCAFBI=4B842E42
